# Generated by Django 4.1.6 on 2023-02-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuses',
            options={'ordering': ['date_created'], 'verbose_name': 'Name', 'verbose_name_plural': 'Names'},
        ),
    ]
