# Generated by Django 4.1.6 on 2023-02-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_alter_statuses_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuses',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Имя'),
        ),
    ]
