# Generated by Django 4.1.6 on 2023-02-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0004_alter_statuses_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statuses',
            new_name='Status',
        ),
    ]
