# Generated by Django 4.1.6 on 2023-02-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0005_rename_statuses_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={},
        ),
        migrations.RenameField(
            model_name='status',
            old_name='date_created',
            new_name='date_create',
        ),
    ]
