# Generated by Django 4.1.6 on 2023-02-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0006_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
    ]
